### ISSUE TITLE
GetAppResult type export missing.

### ISSUE THREAD

**Issue by chinomnsoawazie** [includable/react-native-map-link#275]
Updated the package this morning and noticed `GetAppResult` was no longer available by importing it this way:

  `import {GetAppResult} from 'react-native-map-link'`

Upon closer look, I saw `GetAppsResponse` which had same type signature.  Got my app working again by replacing `GetAppResult` import with `import {GetAppsResponse} from 'react-native-map-link/lib/type'`

**Comment by tschoffelen** [comment]
Fixed in #275

**Comment by chinomnsoawazie** [comment]
> Thanks for flagging this! Would you be able to put in a PR to export this type?

Thanks for the fix. Totally missed your request!

**Comment by viniandrioli** [comment]
use GetAppsResponse instead.

`const [availableApps, setAvailableApps] = useState<GetAppsResponse[]>([]);`

**Comment by lorenc-tomasz** [comment]
Version 3.3.1, `index.d.ts`

```javascript
import { GetAppsProps, GetAppsResponse, MapId, ShowLocationProps } from './type';

export type { DirectionMode, GetAppsProps, GetAppsResponse, MapId, SharedOptions, ShowLocationProps, } from './type';

export { Popup } from './components/popup/Popup';

export type { PopupProps } from './components/popup/Popup';

export declare const showLocation: ({ latitude, longitude, sourceLatitude, sourceLongitude, appleIgnoreLatLon, alwaysIncludeGoogle, googleForceLatLon, googlePlaceId, title: customTitle, app: customApp, dialogTitle: customDialogTitle, dialogMessage: customDialogMessage, cancelText: customCancelText, appsWhiteList: customAppsWhiteList, appTitles, naverCallerName, directionsMode, }: ShowLocationProps) => Promise<MapId | null | undefined>;

export declare function getApps({ alwaysIncludeGoogle, appsWhiteList, appTitles, naverCallerName, ...rest }: GetAppsProps): Promise<GetAppsResponse[]>;

```

GetAppResult is still not exported

**Comment by tschoffelen** [comment]
@lorenc-tomasz I think you need `GetAppsResponse`, as per @viniandrioli's comment above

**Comment by lorenc-tomasz** [comment]
Thanks, didn't notice that the name changed
